// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6EOMh2FTYYFn1a-BzE78lrtHewinAr_w',
    appId: '1:709640396264:web:59f7dd911bf0208c57d85d',
    messagingSenderId: '709640396264',
    projectId: 'smartpathai-b1916',
    authDomain: 'smartpathai-b1916.firebaseapp.com',
    storageBucket: 'smartpathai-b1916.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQG8clEUcPC0s7qVbtQzdLJiRw9u0iIzs',
    appId: '1:709640396264:android:9d174e234d17629157d85d',
    messagingSenderId: '709640396264',
    projectId: 'smartpathai-b1916',
    storageBucket: 'smartpathai-b1916.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBMPX6zJkaZs1BuTveecc3I_bnWmlcqHc',
    appId: '1:709640396264:ios:8a25ffd35baadf4457d85d',
    messagingSenderId: '709640396264',
    projectId: 'smartpathai-b1916',
    storageBucket: 'smartpathai-b1916.firebasestorage.app',
    iosBundleId: 'com.example.smartPathAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBMPX6zJkaZs1BuTveecc3I_bnWmlcqHc',
    appId: '1:709640396264:ios:8a25ffd35baadf4457d85d',
    messagingSenderId: '709640396264',
    projectId: 'smartpathai-b1916',
    storageBucket: 'smartpathai-b1916.firebasestorage.app',
    iosBundleId: 'com.example.smartPathAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6EOMh2FTYYFn1a-BzE78lrtHewinAr_w',
    appId: '1:709640396264:web:01ab4201b792590557d85d',
    messagingSenderId: '709640396264',
    projectId: 'smartpathai-b1916',
    authDomain: 'smartpathai-b1916.firebaseapp.com',
    storageBucket: 'smartpathai-b1916.firebasestorage.app',
  );
}
